# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 12:22
from __future__ import unicode_literals

import aldryn_bootstrap3.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_readmore', '0003_auto_20160812_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmore',
            name='append_icon_closed',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readmore',
            name='append_icon_open',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readmore',
            name='prepend_icon_closed',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readmore',
            name='prepend_icon_open',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
    ]
